# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DMusic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DMusic
  pod 'AlamofireObjectMapper'
  pod 'ReachabilitySwift'
  pod 'Reusable'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'NFDownloadButton'
  pod 'NVActivityIndicatorView'
end
